# Generated by Django 5.0 on 2024-01-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
